database:
  host: artics-db
  username: root
  password: password
  db_name: dev_database
  port: 3306

server:
  name: "artics"
  host: localhost
  port: 8080

mail:
  from: 'info@blail.co.jp'

uploader:
  aws_region: ap-northeast-1
  aws_access_key_id: AKIAUPHKBCYZBMYE6HMU
  aws_secret_access_key: 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
  aws_s3_bucket: artics-s3
