development:
    dialect: mysql
    dir: db/migrations
    datasource: root:password@tcp(artics-db)/dev_database?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
    dialect: postgres
    dir: migrations/postgres
    datasource: dbname=pro_database sslmode=disable
    table: migrations
