version: '3'
services:
  app:
    container_name: artics-app
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - ${APP_PORT}:8080
    volumes:
      - .:/go/artics-api:cached
    tty: true
    depends_on:
      - db
  db:
    container_name: artics-db
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    expose:
      - 6379
    volumes:
      - db_data:/data

volumes:
  db_data:
