// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/content/repository.go

// Package mock_content is a generated GoMock package.
package mock_content

import (
	content "artics-api/src/internal/domain/content"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContentRepository is a mock of ContentRepository interface.
type MockContentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContentRepositoryMockRecorder
}

// MockContentRepositoryMockRecorder is the mock recorder for MockContentRepository.
type MockContentRepositoryMockRecorder struct {
	mock *MockContentRepository
}

// NewMockContentRepository creates a new mock instance.
func NewMockContentRepository(ctrl *gomock.Controller) *MockContentRepository {
	mock := &MockContentRepository{ctrl: ctrl}
	mock.recorder = &MockContentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentRepository) EXPECT() *MockContentRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockContentRepository) Get(ctx context.Context, id int) (*content.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*content.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContentRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContentRepository)(nil).Get), ctx, id)
}

// GetFavoriteContents mocks base method.
func (m *MockContentRepository) GetFavoriteContents(ctx context.Context, userId, limit int) ([]*content.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteContents", ctx, userId, limit)
	ret0, _ := ret[0].([]*content.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteContents indicates an expected call of GetFavoriteContents.
func (mr *MockContentRepositoryMockRecorder) GetFavoriteContents(ctx, userId, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteContents", reflect.TypeOf((*MockContentRepository)(nil).GetFavoriteContents), ctx, userId, limit)
}
