// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNoticeFolloweds(t *testing.T) {
	t.Parallel()

	query := NoticeFolloweds()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNoticeFollowedsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoticeFollowedsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := NoticeFolloweds().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoticeFollowedsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoticeFollowedSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoticeFollowedsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NoticeFollowedExists(ctx, tx, o.NoticeID)
	if err != nil {
		t.Errorf("Unable to check if NoticeFollowed exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NoticeFollowedExists to return true, but got false.")
	}
}

func testNoticeFollowedsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	noticeFollowedFound, err := FindNoticeFollowed(ctx, tx, o.NoticeID)
	if err != nil {
		t.Error(err)
	}

	if noticeFollowedFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNoticeFollowedsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = NoticeFolloweds().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNoticeFollowedsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := NoticeFolloweds().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNoticeFollowedsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	noticeFollowedOne := &NoticeFollowed{}
	noticeFollowedTwo := &NoticeFollowed{}
	if err = randomize.Struct(seed, noticeFollowedOne, noticeFollowedDBTypes, false, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}
	if err = randomize.Struct(seed, noticeFollowedTwo, noticeFollowedDBTypes, false, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noticeFollowedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noticeFollowedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NoticeFolloweds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNoticeFollowedsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	noticeFollowedOne := &NoticeFollowed{}
	noticeFollowedTwo := &NoticeFollowed{}
	if err = randomize.Struct(seed, noticeFollowedOne, noticeFollowedDBTypes, false, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}
	if err = randomize.Struct(seed, noticeFollowedTwo, noticeFollowedDBTypes, false, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noticeFollowedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noticeFollowedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func noticeFollowedBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func noticeFollowedAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *NoticeFollowed) error {
	*o = NoticeFollowed{}
	return nil
}

func testNoticeFollowedsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &NoticeFollowed{}
	o := &NoticeFollowed{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, false); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed object: %s", err)
	}

	AddNoticeFollowedHook(boil.BeforeInsertHook, noticeFollowedBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	noticeFollowedBeforeInsertHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.AfterInsertHook, noticeFollowedAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	noticeFollowedAfterInsertHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.AfterSelectHook, noticeFollowedAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	noticeFollowedAfterSelectHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.BeforeUpdateHook, noticeFollowedBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	noticeFollowedBeforeUpdateHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.AfterUpdateHook, noticeFollowedAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	noticeFollowedAfterUpdateHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.BeforeDeleteHook, noticeFollowedBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	noticeFollowedBeforeDeleteHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.AfterDeleteHook, noticeFollowedAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	noticeFollowedAfterDeleteHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.BeforeUpsertHook, noticeFollowedBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	noticeFollowedBeforeUpsertHooks = []NoticeFollowedHook{}

	AddNoticeFollowedHook(boil.AfterUpsertHook, noticeFollowedAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	noticeFollowedAfterUpsertHooks = []NoticeFollowedHook{}
}

func testNoticeFollowedsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoticeFollowedsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(noticeFollowedColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoticeFollowedToOneNoticeUsingNotice(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local NoticeFollowed
	var foreign Notice

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, noticeFollowedDBTypes, false, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, noticeDBTypes, false, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.NoticeID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Notice().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := NoticeFollowedSlice{&local}
	if err = local.L.LoadNotice(ctx, tx, false, (*[]*NoticeFollowed)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Notice == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Notice = nil
	if err = local.L.LoadNotice(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Notice == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testNoticeFollowedToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local NoticeFollowed
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, noticeFollowedDBTypes, false, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := NoticeFollowedSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*NoticeFollowed)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testNoticeFollowedToOneSetOpNoticeUsingNotice(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a NoticeFollowed
	var b, c Notice

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, noticeFollowedDBTypes, false, strmangle.SetComplement(noticeFollowedPrimaryKeyColumns, noticeFollowedColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, noticeDBTypes, false, strmangle.SetComplement(noticePrimaryKeyColumns, noticeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, noticeDBTypes, false, strmangle.SetComplement(noticePrimaryKeyColumns, noticeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Notice{&b, &c} {
		err = a.SetNotice(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Notice != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.NoticeFollowed != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.NoticeID != x.ID {
			t.Error("foreign key was wrong value", a.NoticeID)
		}

		if exists, err := NoticeFollowedExists(ctx, tx, a.NoticeID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}
func testNoticeFollowedToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a NoticeFollowed
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, noticeFollowedDBTypes, false, strmangle.SetComplement(noticeFollowedPrimaryKeyColumns, noticeFollowedColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.NoticeFolloweds[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testNoticeFollowedsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoticeFollowedsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoticeFollowedSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoticeFollowedsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NoticeFolloweds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	noticeFollowedDBTypes = map[string]string{`NoticeID`: `int`, `UserID`: `int`, `UserThumbnailURL`: `text`, `Body`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_                     = bytes.MinRead
)

func testNoticeFollowedsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(noticeFollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(noticeFollowedAllColumns) == len(noticeFollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNoticeFollowedsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(noticeFollowedAllColumns) == len(noticeFollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NoticeFollowed{}
	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noticeFollowedDBTypes, true, noticeFollowedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(noticeFollowedAllColumns, noticeFollowedPrimaryKeyColumns) {
		fields = noticeFollowedAllColumns
	} else {
		fields = strmangle.SetComplement(
			noticeFollowedAllColumns,
			noticeFollowedPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NoticeFollowedSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNoticeFollowedsUpsert(t *testing.T) {
	t.Parallel()

	if len(noticeFollowedAllColumns) == len(noticeFollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLNoticeFollowedUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := NoticeFollowed{}
	if err = randomize.Struct(seed, &o, noticeFollowedDBTypes, false); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NoticeFollowed: %s", err)
	}

	count, err := NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, noticeFollowedDBTypes, false, noticeFollowedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoticeFollowed struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NoticeFollowed: %s", err)
	}

	count, err = NoticeFolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
