// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Category       string
	Content        string
	Favorite       string
	Follow         string
	GorpMigrations string
	User           string
}{
	Category:       "category",
	Content:        "content",
	Favorite:       "favorite",
	Follow:         "follow",
	GorpMigrations: "gorp_migrations",
	User:           "user",
}
