// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Browses", testBrowses)
	t.Run("Categories", testCategories)
	t.Run("Comments", testComments)
	t.Run("Contents", testContents)
	t.Run("Favorites", testFavorites)
	t.Run("Follows", testFollows)
	t.Run("GorpMigrations", testGorpMigrations)
	t.Run("Notices", testNotices)
	t.Run("NoticeFavorites", testNoticeFavorites)
	t.Run("NoticeFolloweds", testNoticeFolloweds)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Browses", testBrowsesDelete)
	t.Run("Categories", testCategoriesDelete)
	t.Run("Comments", testCommentsDelete)
	t.Run("Contents", testContentsDelete)
	t.Run("Favorites", testFavoritesDelete)
	t.Run("Follows", testFollowsDelete)
	t.Run("GorpMigrations", testGorpMigrationsDelete)
	t.Run("Notices", testNoticesDelete)
	t.Run("NoticeFavorites", testNoticeFavoritesDelete)
	t.Run("NoticeFolloweds", testNoticeFollowedsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Browses", testBrowsesQueryDeleteAll)
	t.Run("Categories", testCategoriesQueryDeleteAll)
	t.Run("Comments", testCommentsQueryDeleteAll)
	t.Run("Contents", testContentsQueryDeleteAll)
	t.Run("Favorites", testFavoritesQueryDeleteAll)
	t.Run("Follows", testFollowsQueryDeleteAll)
	t.Run("GorpMigrations", testGorpMigrationsQueryDeleteAll)
	t.Run("Notices", testNoticesQueryDeleteAll)
	t.Run("NoticeFavorites", testNoticeFavoritesQueryDeleteAll)
	t.Run("NoticeFolloweds", testNoticeFollowedsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Browses", testBrowsesSliceDeleteAll)
	t.Run("Categories", testCategoriesSliceDeleteAll)
	t.Run("Comments", testCommentsSliceDeleteAll)
	t.Run("Contents", testContentsSliceDeleteAll)
	t.Run("Favorites", testFavoritesSliceDeleteAll)
	t.Run("Follows", testFollowsSliceDeleteAll)
	t.Run("GorpMigrations", testGorpMigrationsSliceDeleteAll)
	t.Run("Notices", testNoticesSliceDeleteAll)
	t.Run("NoticeFavorites", testNoticeFavoritesSliceDeleteAll)
	t.Run("NoticeFolloweds", testNoticeFollowedsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Browses", testBrowsesExists)
	t.Run("Categories", testCategoriesExists)
	t.Run("Comments", testCommentsExists)
	t.Run("Contents", testContentsExists)
	t.Run("Favorites", testFavoritesExists)
	t.Run("Follows", testFollowsExists)
	t.Run("GorpMigrations", testGorpMigrationsExists)
	t.Run("Notices", testNoticesExists)
	t.Run("NoticeFavorites", testNoticeFavoritesExists)
	t.Run("NoticeFolloweds", testNoticeFollowedsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Browses", testBrowsesFind)
	t.Run("Categories", testCategoriesFind)
	t.Run("Comments", testCommentsFind)
	t.Run("Contents", testContentsFind)
	t.Run("Favorites", testFavoritesFind)
	t.Run("Follows", testFollowsFind)
	t.Run("GorpMigrations", testGorpMigrationsFind)
	t.Run("Notices", testNoticesFind)
	t.Run("NoticeFavorites", testNoticeFavoritesFind)
	t.Run("NoticeFolloweds", testNoticeFollowedsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Browses", testBrowsesBind)
	t.Run("Categories", testCategoriesBind)
	t.Run("Comments", testCommentsBind)
	t.Run("Contents", testContentsBind)
	t.Run("Favorites", testFavoritesBind)
	t.Run("Follows", testFollowsBind)
	t.Run("GorpMigrations", testGorpMigrationsBind)
	t.Run("Notices", testNoticesBind)
	t.Run("NoticeFavorites", testNoticeFavoritesBind)
	t.Run("NoticeFolloweds", testNoticeFollowedsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Browses", testBrowsesOne)
	t.Run("Categories", testCategoriesOne)
	t.Run("Comments", testCommentsOne)
	t.Run("Contents", testContentsOne)
	t.Run("Favorites", testFavoritesOne)
	t.Run("Follows", testFollowsOne)
	t.Run("GorpMigrations", testGorpMigrationsOne)
	t.Run("Notices", testNoticesOne)
	t.Run("NoticeFavorites", testNoticeFavoritesOne)
	t.Run("NoticeFolloweds", testNoticeFollowedsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Browses", testBrowsesAll)
	t.Run("Categories", testCategoriesAll)
	t.Run("Comments", testCommentsAll)
	t.Run("Contents", testContentsAll)
	t.Run("Favorites", testFavoritesAll)
	t.Run("Follows", testFollowsAll)
	t.Run("GorpMigrations", testGorpMigrationsAll)
	t.Run("Notices", testNoticesAll)
	t.Run("NoticeFavorites", testNoticeFavoritesAll)
	t.Run("NoticeFolloweds", testNoticeFollowedsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Browses", testBrowsesCount)
	t.Run("Categories", testCategoriesCount)
	t.Run("Comments", testCommentsCount)
	t.Run("Contents", testContentsCount)
	t.Run("Favorites", testFavoritesCount)
	t.Run("Follows", testFollowsCount)
	t.Run("GorpMigrations", testGorpMigrationsCount)
	t.Run("Notices", testNoticesCount)
	t.Run("NoticeFavorites", testNoticeFavoritesCount)
	t.Run("NoticeFolloweds", testNoticeFollowedsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Browses", testBrowsesHooks)
	t.Run("Categories", testCategoriesHooks)
	t.Run("Comments", testCommentsHooks)
	t.Run("Contents", testContentsHooks)
	t.Run("Favorites", testFavoritesHooks)
	t.Run("Follows", testFollowsHooks)
	t.Run("GorpMigrations", testGorpMigrationsHooks)
	t.Run("Notices", testNoticesHooks)
	t.Run("NoticeFavorites", testNoticeFavoritesHooks)
	t.Run("NoticeFolloweds", testNoticeFollowedsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Browses", testBrowsesInsert)
	t.Run("Browses", testBrowsesInsertWhitelist)
	t.Run("Categories", testCategoriesInsert)
	t.Run("Categories", testCategoriesInsertWhitelist)
	t.Run("Comments", testCommentsInsert)
	t.Run("Comments", testCommentsInsertWhitelist)
	t.Run("Contents", testContentsInsert)
	t.Run("Contents", testContentsInsertWhitelist)
	t.Run("Favorites", testFavoritesInsert)
	t.Run("Favorites", testFavoritesInsertWhitelist)
	t.Run("Follows", testFollowsInsert)
	t.Run("Follows", testFollowsInsertWhitelist)
	t.Run("GorpMigrations", testGorpMigrationsInsert)
	t.Run("GorpMigrations", testGorpMigrationsInsertWhitelist)
	t.Run("Notices", testNoticesInsert)
	t.Run("Notices", testNoticesInsertWhitelist)
	t.Run("NoticeFavorites", testNoticeFavoritesInsert)
	t.Run("NoticeFavorites", testNoticeFavoritesInsertWhitelist)
	t.Run("NoticeFolloweds", testNoticeFollowedsInsert)
	t.Run("NoticeFolloweds", testNoticeFollowedsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BrowseToContentUsingContent", testBrowseToOneContentUsingContent)
	t.Run("BrowseToUserUsingUser", testBrowseToOneUserUsingUser)
	t.Run("ContentToCategoryUsingCategory", testContentToOneCategoryUsingCategory)
	t.Run("ContentToUserUsingUser", testContentToOneUserUsingUser)
	t.Run("FavoriteToCommentUsingComment", testFavoriteToOneCommentUsingComment)
	t.Run("FavoriteToContentUsingContent", testFavoriteToOneContentUsingContent)
	t.Run("FavoriteToUserUsingUser", testFavoriteToOneUserUsingUser)
	t.Run("FollowToUserUsingFollower", testFollowToOneUserUsingFollower)
	t.Run("FollowToUserUsingFollowing", testFollowToOneUserUsingFollowing)
	t.Run("NoticeToUserUsingUser", testNoticeToOneUserUsingUser)
	t.Run("NoticeFavoriteToContentUsingContent", testNoticeFavoriteToOneContentUsingContent)
	t.Run("NoticeFavoriteToFavoriteUsingFavorite", testNoticeFavoriteToOneFavoriteUsingFavorite)
	t.Run("NoticeFavoriteToNoticeUsingNotice", testNoticeFavoriteToOneNoticeUsingNotice)
	t.Run("NoticeFavoriteToUserUsingUser", testNoticeFavoriteToOneUserUsingUser)
	t.Run("NoticeFollowedToNoticeUsingNotice", testNoticeFollowedToOneNoticeUsingNotice)
	t.Run("NoticeFollowedToUserUsingUser", testNoticeFollowedToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("NoticeToNoticeFavoriteUsingNoticeFavorite", testNoticeOneToOneNoticeFavoriteUsingNoticeFavorite)
	t.Run("NoticeToNoticeFollowedUsingNoticeFollowed", testNoticeOneToOneNoticeFollowedUsingNoticeFollowed)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("CategoryToContents", testCategoryToManyContents)
	t.Run("CommentToFavorites", testCommentToManyFavorites)
	t.Run("ContentToBrowses", testContentToManyBrowses)
	t.Run("ContentToFavorites", testContentToManyFavorites)
	t.Run("ContentToNoticeFavorites", testContentToManyNoticeFavorites)
	t.Run("FavoriteToNoticeFavorites", testFavoriteToManyNoticeFavorites)
	t.Run("UserToBrowses", testUserToManyBrowses)
	t.Run("UserToContents", testUserToManyContents)
	t.Run("UserToFavorites", testUserToManyFavorites)
	t.Run("UserToFollowerFollows", testUserToManyFollowerFollows)
	t.Run("UserToFollowingFollows", testUserToManyFollowingFollows)
	t.Run("UserToNotices", testUserToManyNotices)
	t.Run("UserToNoticeFavorites", testUserToManyNoticeFavorites)
	t.Run("UserToNoticeFolloweds", testUserToManyNoticeFolloweds)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BrowseToContentUsingBrowses", testBrowseToOneSetOpContentUsingContent)
	t.Run("BrowseToUserUsingBrowses", testBrowseToOneSetOpUserUsingUser)
	t.Run("ContentToCategoryUsingContents", testContentToOneSetOpCategoryUsingCategory)
	t.Run("ContentToUserUsingContents", testContentToOneSetOpUserUsingUser)
	t.Run("FavoriteToCommentUsingFavorites", testFavoriteToOneSetOpCommentUsingComment)
	t.Run("FavoriteToContentUsingFavorites", testFavoriteToOneSetOpContentUsingContent)
	t.Run("FavoriteToUserUsingFavorites", testFavoriteToOneSetOpUserUsingUser)
	t.Run("FollowToUserUsingFollowerFollows", testFollowToOneSetOpUserUsingFollower)
	t.Run("FollowToUserUsingFollowingFollows", testFollowToOneSetOpUserUsingFollowing)
	t.Run("NoticeToUserUsingNotices", testNoticeToOneSetOpUserUsingUser)
	t.Run("NoticeFavoriteToContentUsingNoticeFavorites", testNoticeFavoriteToOneSetOpContentUsingContent)
	t.Run("NoticeFavoriteToFavoriteUsingNoticeFavorites", testNoticeFavoriteToOneSetOpFavoriteUsingFavorite)
	t.Run("NoticeFavoriteToNoticeUsingNoticeFavorite", testNoticeFavoriteToOneSetOpNoticeUsingNotice)
	t.Run("NoticeFavoriteToUserUsingNoticeFavorites", testNoticeFavoriteToOneSetOpUserUsingUser)
	t.Run("NoticeFollowedToNoticeUsingNoticeFollowed", testNoticeFollowedToOneSetOpNoticeUsingNotice)
	t.Run("NoticeFollowedToUserUsingNoticeFolloweds", testNoticeFollowedToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("ContentToUserUsingContents", testContentToOneRemoveOpUserUsingUser)
	t.Run("FavoriteToCommentUsingFavorites", testFavoriteToOneRemoveOpCommentUsingComment)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("NoticeToNoticeFavoriteUsingNoticeFavorite", testNoticeOneToOneSetOpNoticeFavoriteUsingNoticeFavorite)
	t.Run("NoticeToNoticeFollowedUsingNoticeFollowed", testNoticeOneToOneSetOpNoticeFollowedUsingNoticeFollowed)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("CategoryToContents", testCategoryToManyAddOpContents)
	t.Run("CommentToFavorites", testCommentToManyAddOpFavorites)
	t.Run("ContentToBrowses", testContentToManyAddOpBrowses)
	t.Run("ContentToFavorites", testContentToManyAddOpFavorites)
	t.Run("ContentToNoticeFavorites", testContentToManyAddOpNoticeFavorites)
	t.Run("FavoriteToNoticeFavorites", testFavoriteToManyAddOpNoticeFavorites)
	t.Run("UserToBrowses", testUserToManyAddOpBrowses)
	t.Run("UserToContents", testUserToManyAddOpContents)
	t.Run("UserToFavorites", testUserToManyAddOpFavorites)
	t.Run("UserToFollowerFollows", testUserToManyAddOpFollowerFollows)
	t.Run("UserToFollowingFollows", testUserToManyAddOpFollowingFollows)
	t.Run("UserToNotices", testUserToManyAddOpNotices)
	t.Run("UserToNoticeFavorites", testUserToManyAddOpNoticeFavorites)
	t.Run("UserToNoticeFolloweds", testUserToManyAddOpNoticeFolloweds)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("CommentToFavorites", testCommentToManySetOpFavorites)
	t.Run("UserToContents", testUserToManySetOpContents)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("CommentToFavorites", testCommentToManyRemoveOpFavorites)
	t.Run("UserToContents", testUserToManyRemoveOpContents)
}

func TestReload(t *testing.T) {
	t.Run("Browses", testBrowsesReload)
	t.Run("Categories", testCategoriesReload)
	t.Run("Comments", testCommentsReload)
	t.Run("Contents", testContentsReload)
	t.Run("Favorites", testFavoritesReload)
	t.Run("Follows", testFollowsReload)
	t.Run("GorpMigrations", testGorpMigrationsReload)
	t.Run("Notices", testNoticesReload)
	t.Run("NoticeFavorites", testNoticeFavoritesReload)
	t.Run("NoticeFolloweds", testNoticeFollowedsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Browses", testBrowsesReloadAll)
	t.Run("Categories", testCategoriesReloadAll)
	t.Run("Comments", testCommentsReloadAll)
	t.Run("Contents", testContentsReloadAll)
	t.Run("Favorites", testFavoritesReloadAll)
	t.Run("Follows", testFollowsReloadAll)
	t.Run("GorpMigrations", testGorpMigrationsReloadAll)
	t.Run("Notices", testNoticesReloadAll)
	t.Run("NoticeFavorites", testNoticeFavoritesReloadAll)
	t.Run("NoticeFolloweds", testNoticeFollowedsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Browses", testBrowsesSelect)
	t.Run("Categories", testCategoriesSelect)
	t.Run("Comments", testCommentsSelect)
	t.Run("Contents", testContentsSelect)
	t.Run("Favorites", testFavoritesSelect)
	t.Run("Follows", testFollowsSelect)
	t.Run("GorpMigrations", testGorpMigrationsSelect)
	t.Run("Notices", testNoticesSelect)
	t.Run("NoticeFavorites", testNoticeFavoritesSelect)
	t.Run("NoticeFolloweds", testNoticeFollowedsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Browses", testBrowsesUpdate)
	t.Run("Categories", testCategoriesUpdate)
	t.Run("Comments", testCommentsUpdate)
	t.Run("Contents", testContentsUpdate)
	t.Run("Favorites", testFavoritesUpdate)
	t.Run("Follows", testFollowsUpdate)
	t.Run("GorpMigrations", testGorpMigrationsUpdate)
	t.Run("Notices", testNoticesUpdate)
	t.Run("NoticeFavorites", testNoticeFavoritesUpdate)
	t.Run("NoticeFolloweds", testNoticeFollowedsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Browses", testBrowsesSliceUpdateAll)
	t.Run("Categories", testCategoriesSliceUpdateAll)
	t.Run("Comments", testCommentsSliceUpdateAll)
	t.Run("Contents", testContentsSliceUpdateAll)
	t.Run("Favorites", testFavoritesSliceUpdateAll)
	t.Run("Follows", testFollowsSliceUpdateAll)
	t.Run("GorpMigrations", testGorpMigrationsSliceUpdateAll)
	t.Run("Notices", testNoticesSliceUpdateAll)
	t.Run("NoticeFavorites", testNoticeFavoritesSliceUpdateAll)
	t.Run("NoticeFolloweds", testNoticeFollowedsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
