// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Browse         string
	Category       string
	Comment        string
	Content        string
	Favorite       string
	Follow         string
	GorpMigrations string
	Notice         string
	User           string
}{
	Browse:         "browse",
	Category:       "category",
	Comment:        "comment",
	Content:        "content",
	Favorite:       "favorite",
	Follow:         "follow",
	GorpMigrations: "gorp_migrations",
	Notice:         "notice",
	User:           "user",
}
