// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNotices(t *testing.T) {
	t.Parallel()

	query := Notices()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNoticesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoticesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Notices().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoticesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoticeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoticesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NoticeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Notice exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NoticeExists to return true, but got false.")
	}
}

func testNoticesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	noticeFound, err := FindNotice(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if noticeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNoticesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Notices().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNoticesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Notices().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNoticesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	noticeOne := &Notice{}
	noticeTwo := &Notice{}
	if err = randomize.Struct(seed, noticeOne, noticeDBTypes, false, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}
	if err = randomize.Struct(seed, noticeTwo, noticeDBTypes, false, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noticeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noticeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Notices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNoticesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	noticeOne := &Notice{}
	noticeTwo := &Notice{}
	if err = randomize.Struct(seed, noticeOne, noticeDBTypes, false, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}
	if err = randomize.Struct(seed, noticeTwo, noticeDBTypes, false, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noticeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noticeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func noticeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func noticeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Notice) error {
	*o = Notice{}
	return nil
}

func testNoticesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Notice{}
	o := &Notice{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, noticeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Notice object: %s", err)
	}

	AddNoticeHook(boil.BeforeInsertHook, noticeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	noticeBeforeInsertHooks = []NoticeHook{}

	AddNoticeHook(boil.AfterInsertHook, noticeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	noticeAfterInsertHooks = []NoticeHook{}

	AddNoticeHook(boil.AfterSelectHook, noticeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	noticeAfterSelectHooks = []NoticeHook{}

	AddNoticeHook(boil.BeforeUpdateHook, noticeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	noticeBeforeUpdateHooks = []NoticeHook{}

	AddNoticeHook(boil.AfterUpdateHook, noticeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	noticeAfterUpdateHooks = []NoticeHook{}

	AddNoticeHook(boil.BeforeDeleteHook, noticeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	noticeBeforeDeleteHooks = []NoticeHook{}

	AddNoticeHook(boil.AfterDeleteHook, noticeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	noticeAfterDeleteHooks = []NoticeHook{}

	AddNoticeHook(boil.BeforeUpsertHook, noticeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	noticeBeforeUpsertHooks = []NoticeHook{}

	AddNoticeHook(boil.AfterUpsertHook, noticeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	noticeAfterUpsertHooks = []NoticeHook{}
}

func testNoticesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoticesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(noticeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoticeToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Notice
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, noticeDBTypes, false, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := NoticeSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Notice)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testNoticeToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Notice
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, noticeDBTypes, false, strmangle.SetComplement(noticePrimaryKeyColumns, noticeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Notices[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testNoticesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoticesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoticeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoticesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Notices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	noticeDBTypes = map[string]string{`ID`: `int`, `UserID`: `int`, `Title`: `varchar`, `Body`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_             = bytes.MinRead
)

func testNoticesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(noticePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(noticeAllColumns) == len(noticePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNoticesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(noticeAllColumns) == len(noticePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Notice{}
	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noticeDBTypes, true, noticePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(noticeAllColumns, noticePrimaryKeyColumns) {
		fields = noticeAllColumns
	} else {
		fields = strmangle.SetComplement(
			noticeAllColumns,
			noticePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NoticeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNoticesUpsert(t *testing.T) {
	t.Parallel()

	if len(noticeAllColumns) == len(noticePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLNoticeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Notice{}
	if err = randomize.Struct(seed, &o, noticeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Notice: %s", err)
	}

	count, err := Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, noticeDBTypes, false, noticePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Notice struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Notice: %s", err)
	}

	count, err = Notices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
